Parameters:
  ProjectName:
    Type: String
    Default: user-service-build
    Description: Name of the CodeBuild project

Resources:
  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ProjectName}-service-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonECR_FullAccess
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess

  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Ref ProjectName
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:4.0
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: AWS_DEFAULT_REGION
            Value: ap-northeast-2
          - Name: AWS_ACCOUNT_ID
            Value: '463470980614'
      Source:
        Type: GITHUB
        Location: https://github.com/Nimbus-2025/gaenchwis.git
        BuildSpec: server/user_service/buildspec.yml
