Resources:
  #Job Posting Backend Service
  JobPostingBackendService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !ImportValue ECSCluster
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 50
        Alarms:
          AlarmNames:
            - Job Posting Backend Alarm
          Enable: true
          Rollback: true
      DesiredCount: 1
      LoadBalancers:
        - ContainerName: Gaenchwis-JobPostingBackend
          ContainerPort: 8003
          TargetGroupArn: !ImportValue BackendTargetGroup8003
      PlacementStrategies:
        - Type: binpack
          Field: memory
      TaskDefinition: !Ref JobPostingBackendTask
      ServiceName: JobPostingBackendService
      Role: !ImportValue ECSServiceRole
  #Job Posting Backend Task
  JobPostingBackendTask:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Name: Gaenchwis-JobPostingBackend
          Image: 463470980614.dkr.ecr.ap-northeast-2.amazonaws.com/gaenchwis/job-posting-service:latest
          PortMappings:
            - ContainerPort: 8003
              HostPort: 8003
              Protocol: tcp
          Environment:
            - Name: COGNITO_USER_POOL_ID
              Value: ap-northeast-2_ltCxps5XQ
            - Name: COGNITO_APP_CLIENT_ID
              Value: 6dnsfj8d7327ghh5sg62eqbru0
            - Name: AWS_REGION
              Value: ap-northeast-2
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: ap-northeast-2
              awslogs-group: !ImportValue BackendLogGroup
              awslogs-stream-prefix: ecs-backend
      Family: Gaenchwis-JobPostingBackend
      Cpu: 512
      Memory: 1024
      TaskRoleArn: !ImportValue ECSContainerRole
      ExecutionRoleArn: !ImportValue ECSContainerExecutionRole
