Resources:
  #Frontend Service
  FrontendService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !ImportValue ECSCluster
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 50
        Alarms:
          AlarmNames:
            - Frontend Alarm
          Enable: true
          Rollback: true
      DesiredCount: 1
      LoadBalancers:
        - ContainerName: Gaenchwis-Frontend
          ContainerPort: 80
          TargetGroupArn: !ImportValue FrontendTargetGroup
      PlacementStrategies:
        - Type: binpack
          Field: memory
      TaskDefinition: !Ref FrontendTask
      ServiceName: FrontendService
      Role: !ImportValue ECSServiceRole
  #Frontend Task
  FrontendTask:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Name: Gaenchwis-Frontend
          Image: 463470980614.dkr.ecr.ap-northeast-2.amazonaws.com/gaenchwis/client-service:latest
          PortMappings:
            - HostPort: 80
              ContainerPort: 80
              Protocol: tcp
          Environment:
            - Name: ALB
              Value: !ImportValue ApplicationLoadBalancer
            - Name: COGNITO_USER_POOL_ID
              Value: ap-northeast-2_ltCxps5XQ
            - Name: COGNITO_APP_CLIENT_ID
              Value: 6dnsfj8d7327ghh5sg62eqbru0
            - Name: AWS_REGION
              Value: ap-northeast-2
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: ap-northeast-2
              awslogs-group: !ImportValue FrontendLogGroup
              awslogs-stream-prefix: ecs-frontend
      Family: Gaenchwis-Frontend
      Cpu: 512
      Memory: 512
      TaskRoleArn: !ImportValue ECSContainerRole
      ExecutionRoleArn: !ImportValue ECSContainerExecutionRole
