version: 0.2

phases:
  install:
    commands:
      - echo Installing prerequisites...
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_REGION=$AWS_DEFAULT_REGION
      - AWS_ACCOUNT_ID=$AWS_ACCOUNT_ID
      - COGNITO_USER_POOL_ID=$COGNITO_USER_POOL_ID
      - COGNITO_APP_CLIENT_ID=$COGNITO_APP_CLIENT_ID

  pre_build:
    commands:
      # ECR 로그인
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      # 환경변수 설정
      - REPOSITORY_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/gaenchwis/user-service
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}

  build:
    commands:
      # Docker 이미지 빌드
      - echo Building the Docker image...
      - pwd
      - ls -la
      - cd server/user_service
      # - cat Dockerfile
      - cd $CODEBUILD_SRC_DIR
      - ls -la
      - cd server/user_service
      - ls -la
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG -f Dockerfile . --progress=plain
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:latest

  post_build:
    commands:
      # ECR에 이미지 푸시
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest
      # ECS 배포를 위한 imagedefinitions.json 생성
      - pwd
      - echo Writing image definitions file...
      - printf '[{"name":"Gaenchwis-UserBackend","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > $CODEBUILD_SRC_DIR/imageDefinitions.json
      # task-definition.json의 환경변수 치환
      - cd $CODEBUILD_SRC_DIR/server/user_service
      - envsubst < ./task-definition.json > $CODEBUILD_SRC_DIR/task-definition.json

artifacts:
  files:
    - task-definition.json
    - imageDefinitions.json
  base-directory: $CODEBUILD_SRC_DIR/
  discard-paths: yes

env:
  parameter-store:
    ACCOUNT_ID: /gaenchwis/user-service/account-id
    AWS_REGION: /gaenchwis/user-service/aws-region
    COGNITO_USER_POOL_ID: /gaenchwis/user-service/cognito-user-pool-id
    COGNITO_APP_CLIENT_ID: /gaenchwis/user-service/cognito-app-client-id
