const dummyJobListings = [
    {
      _id: '1',
      title: '프론트엔드 개발자',
      location: '서울',
      description: 'React와 Redux를 사용한 웹 애플리케이션 개발.',
      company: 'ABC Corp',
      experienceLevel: '신입',
    },
    {
      _id: '2',
      title: '백엔드 개발자',
      location: '부산',
      description: 'Node.js와 MongoDB를 사용한 API 개발.',
      company: 'XYZ Inc',
      experienceLevel: '경력',
    },
    {
      _id: '3',
      title: 'UI/UX 디자이너',
      location: '대전',
      description: '사용자 경험을 고려한 디자인 작업.',
      company: 'Design Studio',
      experienceLevel: '신입',
    },
    {
      _id: '4',
      title: '데이터 분석가',
      location: '서울',
      description: 'Python을 사용한 데이터 분석 및 시각화.',
      company: 'Data Solutions',
      experienceLevel: '경력',
    },
    {
      _id: '5',
      title: '풀스택 개발자',
      location: '제주',
      description: '프론트엔드와 백엔드 모두를 다루는 개발자.',
      company: 'Tech Innovations',
      experienceLevel: '신입',
    },
    {
      _id: '6',
      title: '모바일 앱 개발자',
      location: '인천',
      description: 'iOS 및 Android 앱 개발.',
      company: 'Mobile Solutions',
      experienceLevel: '경력',
    },
    {
      _id: '7',
      title: 'DevOps 엔지니어',
      location: '광주',
      description: 'CI/CD 파이프라인 구축 및 관리.',
      company: 'Cloud Services',
      experienceLevel: '신입',
    },
    {
      _id: '8',
      title: 'QA 엔지니어',
      location: '대구',
      description: '소프트웨어 품질 보증 및 테스트.',
      company: 'Quality Assurance Co.',
      experienceLevel: '경력',
    },
    {
      _id: '9',
      title: '시스템 관리자',
      location: '서울',
      description: '서버 및 네트워크 관리.',
      company: 'IT Solutions',
      experienceLevel: '신입',
    },
    {
      _id: '10',
      title: '게임 개발자',
      location: '부산',
      description: '게임 디자인 및 개발.',
      company: 'Game Studio',
      experienceLevel: '경력',
    },
  ];
  
  export default dummyJobListings;