version: 0.2

phases:
  install:
    commands:
      - echo Installing prerequisites...
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - yum install -y git
      - git config --global protocol.version 2

  pre_build:
    commands:
      - |
        # 모든 검사 로직을 하나의 블록으로 묶습니다
        echo "Event = $CODEBUILD_WEBHOOK_EVENT"

        if [ "$CODEBUILD_WEBHOOK_EVENT" = "PULL_REQUEST_CREATED" ] || [ "$CODEBUILD_WEBHOOK_EVENT" = "PULL_REQUEST_UPDATED" ]; then
          echo "Processing Pull Request..."
          git fetch --unshallow || true
          git fetch origin '+refs/heads/*:refs/remotes/origin/*'
          BEFORE_COMMIT_ID=$(echo $CODEBUILD_WEBHOOK_PREV_COMMIT)
          AFTER_COMMIT_ID=$(echo $CODEBUILD_WEBHOOK_HEAD_REF)
          echo "Comparing $BEFORE_COMMIT_ID with $AFTER_COMMIT_ID"
          CHANGED_FILES=$(git diff --name-only $BEFORE_COMMIT_ID $AFTER_COMMIT_ID)
        elif [ "$CODEBUILD_WEBHOOK_EVENT" = "PUSH" ]; then
          echo "Processing Push..."
          CHANGED_FILES=$(git diff --name-only HEAD^)
        else
          echo "Default case..."
          CHANGED_FILES=""
        fi

        if [ -z "$CHANGED_FILES" ]; then
          echo "No changed files detected, skipping build..."
          exit 1
        fi

        if ! echo "$CHANGED_FILES" | grep -q "^server/essay_service/"; then
          echo "No changes in essay_service directory, skipping build..."
          exit 1
        fi

        # 여기까지 왔다면 빌드를 진행해야 하는 경우입니다
        echo "Changes detected in essay_service directory, proceeding with build..."

        # ECR 로그인
        echo "Logging in to Amazon ECR..."
        aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

        # 환경변수 설정
        REPOSITORY_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/gaenchwis/essay-service
        COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
        IMAGE_TAG=${COMMIT_HASH:=latest}

        # 환경변수를 다음 단계에서 사용할 수 있도록 export
        echo "REPOSITORY_URI=$REPOSITORY_URI" >> $CODEBUILD_SRC_DIR/build.env
        echo "IMAGE_TAG=$IMAGE_TAG" >> $CODEBUILD_SRC_DIR/build.env

  build:
    commands:
      - . $CODEBUILD_SRC_DIR/build.env
      - echo Building the Docker image...
      - cd server/essay_service
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG -f Dockerfile . --progress=plain
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:latest

  post_build:
    commands:
      - . $CODEBUILD_SRC_DIR/build.env
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest
      - echo Writing image definitions file...
      - printf '[{"name":"Gaenchwis-EssayBackend","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > $CODEBUILD_SRC_DIR/imageDefinitions.json
      - envsubst < ./task-definition.json > $CODEBUILD_SRC_DIR/task-definition.json

artifacts:
  files:
    - task-definition.json
    - imageDefinitions.json
  base-directory: $CODEBUILD_SRC_DIR/
  discard-paths: yes
