AWSTemplateFormatVersion: '2010-09-09'
Description: 'ECR Repository for User Service'

Resources:
  UserServiceRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: gaenchwis/user-service
      ImageScanningConfiguration:
        ScanOnPush: true
      ImageTagMutability: MUTABLE
      EncryptionConfiguration:
        EncryptionType: AES256
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep last 5 images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 5
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }

Outputs:
  RepositoryUri:
    Description: URI for User Service Repository
    Value: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${UserServiceRepository}
    Export:
      Name: !Sub ${AWS::StackName}-UserServiceRepositoryUri

  RepositoryName:
    Description: Name of User Service Repository
    Value: !Ref UserServiceRepository
    Export:
      Name: !Sub ${AWS::StackName}-UserServiceRepositoryName
